title: Shihao Wang's Professional Portfolio
email: shihaowang369@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the professional portfolio of Shihao Wang, Ph.D., showcasing expertise in robotics and autonomous vehicle technology.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shihaorobotics.github.io" # the base hostname & protocol for your site
github_username:  shihaorobotics

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
